import SwiftUI
// MARK: - Agent Model
struct Agent: Equatable {
    var name: String
    var role: String
    var abilities: [String] // List of abilities
    var faceImage: String   // Image name from Assets.xcassets
    var bio: String         // Description of the agent's lore
    
    // Static list of available agents
    static let allAgents = [
            Agent(name: "Astra", role: "CONTROLLER", abilities: ["Gravity Well", "Nova Pulse", "Nebula", "Cosmic Divide"], faceImage: "astra_face", bio: "Ghanaian Agent Astra harnesses the energies of the cosmos to reshape battlefields to her whim. With full command of her astral form and a talent for deep strategic foresight."),
            Agent(name: "Breach", role: "INITIATOR", abilities: ["Aftershock", "Flashpoint", "Fault Line", "Rolling Thunder"], faceImage: "breach_face", bio: "Breach, the bionic Swede, fires powerful, targeted kinetic blasts to aggressively clear a path through enemy ground. The damage and disruption he inflicts ensures no fight is ever fair."),
            Agent(name: "Brimstone", role: "CONTROLLER", abilities: ["Incendiary", "Stim Beacon", "Sky Smoke", "Orbital Strike"], faceImage: "brimstone_face", bio: "Joining from the U.S.A., Brimstone's orbital arsenal ensures his squad always has the advantage. His ability to deliver utility precisely and from a distance make him an unmatched boots-on-the-ground commander."),
            Agent(name: "Chamber", role: "SENTINEL", abilities: ["Trademark", "Headhunter", "Rendezvous", "Tour de Force"], faceImage: "chamber_face", bio: "Well-dressed and well-armed, French weapons designer Chamber expels aggressors with deadly precision. He leverages his custom arsenal to hold the line and pick off enemies from afar, with a contingency built for every plan."),
            Agent(name: "Clove", role: "CONTROLLER", abilities: ["Meddle", "Pick-me-up", "Ruse", "Not Dead Yet"], faceImage: "clove_face", bio: "Scottish troublemaker Clove makes mischief for enemies in both the heat of combat and the cold of death. The young immortal keeps foes guessing, even from beyond the grave, their return to the living only ever a moment away."),
            Agent(name: "Cypher", role: "SENTINEL", abilities: ["Trapwire", "Cyber Cage", "Spycam", "Neural Theft"], faceImage: "cypher_face", bio: "The Moroccan information broker, Cypher is a one-man surveillance network who keeps tabs on the enemy’s every move. No secret is safe. No maneuver goes unseen. Cypher is always watching."),
            Agent(name: "Deadlock", role: "SENTINEL", abilities: ["GravNet", "Sonic Sensor", "Barrier Mesh", "Annihilation"], faceImage: "deadlock_face", bio: "Norwegian operative Deadlock deploys an array of cutting-edge nanowire to secure the battlefield from even the most lethal assault. No one escapes her vigilant watch, nor survives her unyielding ferocity."),
            Agent(name: "Fade", role: "INITIATOR", abilities: ["Prowler", "Seize", "Haunt", "Nightfall"], faceImage: "fade_face", bio: "Turkish bounty hunter Fade unleashes the power of raw nightmare to seize enemy secrets. Attuned with terror itself, she hunts down targets and reveals their deepest fears - before crushing them in the dark."),
            Agent(name: "Gekko", role: "INITIATOR", abilities: ["Dizzy", "Wingman", "Mosh Pit", "Thrash"], faceImage: "gekko_face", bio: "Gekko the Angeleno leads a tight-knit crew of calamitous creatures. His buddies bound forward, scattering enemies out of the way, with Gekko chasing them down to regroup and go again."),
            Agent(name: "Harbor", role: "CONTROLLER", abilities: ["Cascade", "Cove", "High Tide", "Reckoning"], faceImage: "harbor_face", bio: "Hailing from India's coast, Harbor storms the field wielding ancient technology with dominion over water. He unleashes frothing rapids and crushing waves to shield his allies, or pummel those that oppose him."),
            Agent(name: "Iso", role: "DUELIST", abilities: ["Undercut", "Contingency", "Double Tap", "Kill Contract"], faceImage: "iso_face", bio: "Chinese fixer for hire Iso goes into a flow state to dismantle the opposition. Reconfiguring ambient energy into bulletproof protection, he advances with focus towards his next duel to the death."),
            Agent(name: "Jett", role: "DUELIST", abilities: ["Cloudburst", "Updraft", "Tailwind", "Blade Storm"], faceImage: "jett_face", bio: "Representing her home country of South Korea, Jett's agile and evasive fighting style lets her take risks no one else can. She runs circles around every skirmish, cutting enemies before they even know what hit them."),
            Agent(name: "KAY/O", role: "INITIATOR", abilities: ["FRAG/ment", "FLASH/drive", "ZERO/point", "NULL/cmd"], faceImage: "kayo_face", bio: "KAY/O is a machine of war built for a single purpose: neutralizing radiants. His power to suppress enemy abilities dismantles his opponents' capacity to fight back, securing him and his allies the ultimate edge."),
            Agent(name: "Killjoy", role: "SENTINEL", abilities: ["Nanoswarm", "Alarmbot", "Turret", "Lockdown"], faceImage: "killjoy_face", bio: "The genius of Germany, Killjoy effortlessly secures key battlefield positions with her arsenal of inventions. If their damage doesn't take her enemies out, the debuff her robots provide will make short work of them."),
            Agent(name: "Neon", role: "DUELIST", abilities: ["High Gear", "Relay Bolt", "Fast Lane", "Overdrive"], faceImage: "neon_face", bio: "Filipino Agent, Neon, surges forward at shocking speeds, discharging bursts of bioelectric radiance as fast as her body generates it. She races ahead to catch enemies off guard, then strikes them down quicker than lightning."),
            Agent(name: "Omen", role: "CONTROLLER", abilities: ["Shrouded Step", "Paranoia", "Dark Cover", "From the Shadows"], faceImage: "omen_face", bio: "A phantom of a memory, Omen hunts in the shadows. He renders enemies blind, teleports across the field, then lets paranoia take hold as his foe scrambles to learn where he might strike next."),
            Agent(name: "Phoenix", role: "DUELIST", abilities: ["Blaze", "Curveball", "Hot Hands", "Run It Back"], faceImage: "phoenix_face", bio: "Hailing from the U.K., Phoenix's star power shines through in his fighting style, igniting the battlefield with flash and flare. Whether he's got backup or not, he'll rush into a fight on his own terms."),
            Agent(name: "Raze", role: "DUELIST", abilities: ["Boom Bot", "Paint Shells", "Blast Pack", "Showstopper"], faceImage: "raze_face", bio: "Raze explodes out of Brazil with her big personality and big guns. With her blunt-force-trauma playstyle, she excels at flushing entrenched enemies and clearing tight spaces with a generous dose of “boom.”"),
            Agent(name: "Reyna", role: "DUELIST", abilities: ["Leer", "Devour", "Dismiss", "Empress"], faceImage: "reyna_face", bio: "Forged in the heart of Mexico, Reyna dominates single combat, popping off with each kill she scores. Her capability is only limited by her raw skill, making her highly dependent on performance."),
            Agent(name: "Sage", role: "SENTINEL", abilities: ["Barrier Orb", "Slow Orb", "Healing Orb", "Resurrection"], faceImage: "sage_face", bio: "The bastion of China, Sage creates safety for herself and her team wherever she goes. Able to revive fallen friends and stave off aggressive pushes, she provides a calm center to a hellish fight."),
            Agent(name: "Skye", role: "INITIATOR", abilities: ["Regrowth", "Trailblazer", "Guiding Light", "Seekers"], faceImage: "skye_face", bio: "Hailing from Australia, Skye and her band of beasts trail-blaze the way through hostile territory. With her creations hampering the enemy, and her power to heal others, the team is strongest and safest by Skye's side."),
            Agent(name: "Sova", role: "INITIATOR", abilities: ["Owl Drone", "Shock Bolt", "Recon Bolt", "Hunter's Fury"], faceImage: "sova_face", bio: "Born from the eternal winter of Russia's tundra, Sova tracks, finds, and eliminates enemies with ruthless efficiency and precision. His custom bow and incredible scouting abilities ensure that even if you run, you cannot hide."),
            Agent(name: "Tejo", role: "INITIATOR", abilities: ["Stealth Drone", "Special Delivery", "Guided Salvo", "Armageddon"], faceImage: "tejo_face", bio: "A veteran intelligence consultant from Colombia, Tejo’s ballistic guidance system pressures the enemy to relinquish their ground - or their lives. His targeted strikes keep opponents off balance and under his heel."),
            Agent(name: "Viper", role: "CONTROLLER", abilities: ["Snake Bite", "Poison Cloud", "Toxic Screen", "Viper's Pit"], faceImage: "viper_face", bio: "The American chemist, Viper deploys an array of poisonous chemical devices to control the battlefield and choke the enemy's vision. If the toxins don't kill her prey, her mind games surely will."),
            Agent(name: "Vyse", role: "SENTINEL", abilities: ["Shear", "Razorvine", "Arc Rose", "Steel Garden"], faceImage: "vyse_face", bio: "Metallic mastermind Vyse unleashes liquid metal to isolate, trap, and disarm her enemies. Through cunning and manipulation, she forces all who oppose her to fear the battlefield itself."),
            Agent(name: "Yoru", role: "DUELIST", abilities: ["Fakeout", "Blindside", "Gatecrash", "Dimensional Drift"], faceImage: "yoru_face", bio: "Japanese native Yoru rips holes straight through reality to infiltrate enemy lines unseen. Using deception and aggression in equal measure, he gets the drop on each target before they know where to look.")
        ]
}
